baseURL = "http://wanq.me/"
languageCode = "en"
title = "WanQ Notes"

[Params]
subtitle = "life·code·product"
github = "https://github.com/cnwanq"
profile = "/images/profile.png"
copyright = "Written by wanq"